### ISSUE TITLE
Things to Help with Locking Down OS

### ISSUE THREAD

**Issue by 53142** [Bit-Programming/Pomoimprove#2]
https://www.howtogeek.com/howto/8739/restrict-users-to-run-only-specified-programs-in-windows-7/
(Change the registry to block things from opening. I think that this can be done in Python)

https://www.reddit.com/r/learnpython/comments/2w6udp/python_on_windows_how_to_block_other_programs/

**Comment by UHDbits** [comment]
"lockdown.py" is finished.
